dist: bionic
language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
    - public/assets
    - /home/travis/.rvm/gems
    - /home/travis/.cache/rubocop_cache
env:
  global:
    - RAILS_ENV=test
services:
  - postgresql
addons:
  postgresql: '9.6'
sudo: true
before_install:
  - gem install bundler
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install clamav clamav-daemon
  - sudo apt-get install -y postgresql-9.6-postgis-2.4
  - psql -U postgres -c 'create database marketplace_test'
  - psql -U postgres -d marketplace_test -c 'create extension postgis'
  - sudo systemctl stop clamav-freshclam.service
  - sudo chown -R $USER:$USER /etc/clamav/clamd.conf
  - sudo echo TCPADDR $CLAMAV_SERVER_ADDRESS >> /etc/clamav/clamd.conf
  - sudo echo TCPPORT 3310 >> /etc/clamav/clamd.conf
  - sudo service clamd restart
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake assets:precompile
  - bundle exec rake
  - rm public/assets/.sprockets-manifest-*.json
notifications:
  webhooks: https://api.eu.opsgenie.com/v1/json/travisci?apiKey=430b3a4a-eeba-486e-9133-99083dde9787
