name: "Analyse Ruby code with RuboCop and Brakeman and JavaScript code with ESLint"

on:
  workflow_call:

jobs:
  code_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1.256.0
        with:
          bundler-cache: true

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.18

      - name: Run rubocop
        run: bin/rubocop
      
      - name: Check JavaScript code quality
        run: |
          bun install
          bun lint
          bun typecheck

      # To be added in the future
      # - name: Run brakeman
      #   run: bin/brakeman
